spring:
  application:
    name: teamwork_management

  security:
    user:
      name: admin
      password: admin123
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
        provider:
            google:
                authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
                token-uri: https://oauth2.googleapis.com/token
                user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
                user-name-attribute: sub

  datasource:
    url: jdbc:mysql://localhost:3307/teamwork_management?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: ${SPRING_FILE_MAX_FILE_SIZE:10MB}
      max-request-size: ${SPRING_FILE_MAX_REQUEST_SIZE:10MB}
      location: ${java.io.tmpdir}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  jwt:
    secret: 263480134625fe78955ba600bd2ef5b9
    expiration: 3600 # 1 hour
    token-prefix: Bearer
    header-string: Authorization

  file:
    upload-dir: ${SPRING_FILE_UPLOAD_DIR:/app/uploads}
    max-file-size: ${SPRING_FILE_MAX_FILE_SIZE:10MB}
    max-request-size: ${SPRING_FILE_MAX_REQUEST_SIZE:10MB}

  logging:
    level:
      org.springframework.web: DEBUG
      org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

